<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'name' => 'ホスティングサービス設定',
                'category' => 5,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'サーバーメンテナンス',
                'category' => 5,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'セキュリティ設定',
                'category' => 5,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'スケーラビリティ計画',
                'category' => 5,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'テキストコンテンツ作成',
                'category' => 6,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => '画像/動画コンテンツ作成',
                'category' => 6,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'コンテンツレビュー',
                'category' => 6,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'SEO最適化',
                'category' => 6,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => '単体テスト',
                'category' => 7,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => '統合テスト',
                'category' => 7,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'システムテスト',
                'category' => 7,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'ユーザビリティテスト',
                'category' => 7,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'バグ修正',
                'category' => 7,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'デプロイメント準備',
                'category' => 8,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'デプロイメント実行',
                'category' => 8,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'デプロイメント後のチェック',
                'category' => 8,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'バックアップ作成',
                'category' => 8,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => '定期メンテナンス',
                'category' => 9,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => '問い合わせ対応',
                'category' => 9,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'パフォーマンス監視',
                'category' => 9,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'セキュリティアップデート',
                'category' => 9,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'プロジェクトドキュメント作成',
                'category' => 10,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'コードドキュメント作成',
                'category' => 10,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'ユーザーマニュアル作成',
                'category' => 10,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            [
                'name' => 'トレーニング資料作成',
                'category' => 10,
                'diff_low' => 20000,
                'diff_mid' => 32000,
                'diff_high' => 48000,
                'acc_low' => 30,
                'acc_mid' => 10,
                'acc_high' => 0,
                'cost_low' => 0,
                'cost_mid' => 10,
                'cost_high' => 20,
                'risk_low' => 10,
                'risk_mid' => 15,
                'risk_high' => 20,
                'memo' => ''
            ],
            // 他の初期データをここに追加
        ];

        foreach ($items as $item) {
            Item::create($item);
        }
    }
}
